builtins       = ["_"]
preview        = true
target-version = "py313"
unsafe-fixes   = true

[analyze]
    preview = true

[format]
    docstring-code-format     = true
    line-ending               = "lf"
    preview                   = true
    skip-magic-trailing-comma = true

[lint]
    future-annotations = true
    ignore = [
        "COM812",
        "COM819",
        "CPY001",
        "D203",
        "D206",
        "D207",
        "D208",
        "D212",
        "D300",
        "E111",
        "E114",
        "E117",
        "PLR0913",
        "PLR0917",
        "Q000",
        "Q001",
        "Q002",
        "Q003",
        "Q004",
        "S404",
        "S602",
        "S603",
        "W191",
    ]
    select = ["ALL"]
    typing-extensions = false
    unfixable = ["T201"]

    [lint.isort]
        split-on-trailing-comma = false
